#include <iostream>
#include "opengl.hpp"

namespace BnZ {

    bool initGL() {
        glewExperimental = GL_TRUE;
        GLenum error;
        if (GLEW_OK != (error = glewInit())) {
            std::cerr << "glewInit() error: " << glewGetErrorString(error) << std::endl;
            return false;
        }
        glGetError(); // Pop the GL error generated by GLEW with CORE PROFILE (if any)
        return true;
    }

}
